media:
  input: pics
  output: /pics

content:
  - name: articles
    collection: articles
    path: articles
    fields:
      - name: title
        type: string
      - name: slug
        type: string
      - name: date
        type: string
      - name: cover
        type: string
      - name: categories
        type: list
        subtype: string
      - name: authors
        type: string
      - name: content
        type: markdown
      - name: trending
        type: boolean
      - name: featured
        type: boolean

  - name: published
    collection: published
    path: articles/index.json
    fields:
      - name: published
        type: list
        subtype: string
