backend:
  name: proxy
  repo: "zeyad-sukkary/Z-A-S"
  branch: main
  proxy_url: https://decap-cms-auth.onrender.com/auth
  auth_endpoint: https://decap-cms-auth.onrender.com/auth


site_url: https://zeyad-sukkary.github.io/Z-A-S
base_url: /Z-A-S

media_folder: "pics"
public_folder: "/Z-A-S/pics"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    extension: "json"
    format: "json"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime", format: "DD/MM/YY" }
      - { name: "cover", label: "Cover Image", widget: "image" }
      - { name: "categories", label: "Categories", widget: "list", default: [] }
      - { name: "authors", label: "Authors", widget: "string" }
      - { name: "content", label: "Content", widget: "markdown" }
      - { name: "trending", label: "Trending", widget: "boolean", default: false }
      - { name: "featured", label: "Featured", widget: "boolean", default: false }
 
  - name: "articleIndex"
    label: "Published Articles"
    files:
      - file: "articles/index.json"
        label: "Article Index"
        name: "index"
        fields:
          - label: "Published Articles"
            name: "published"
            widget: "list"
            summary: "{{fields.published}}"
            field: { label: "Filename", name: "Published Article", widget: "string" }
